### ISSUE TITLE
Fix checkpatch_wrapper test

### ISSUE THREAD

**Issue by matheustavares** [rodrigosiqueira/kworkflow#122]
The `tests/checkpatch_wrapper.sh` has currently some problems which prevents it from working correctly. The minor one is replacing `assertFail` for `assertFalse`. The major one is that the test file didn't learned that kw now uses the local checkpatch.pl script. In this sense, the tests still assume a `~/.config/kw/external/checkpatch.pl` script and should in fact, be failing. The fact that it's succeeding is a bug.

To better understand the problem, we can print the `$res` variable at function `checkpatch`. It always contains `"Neither the given path nor the working path is in a kernel tree."`, not the expected strings.

**Comment by rodrigosiqueira** [comment]
I already merged #123
