### ISSUE TITLE
Return error exit code on failure

### ISSUE THREAD

**Issue by RenatoGeh** [rodrigosiqueira/kworkflow#19]
As of now, whenever kw fails (e.g. not in kernel root when running `kw maintainers` or invalid path for `kw codestyle`) the script complains, but returns a zero exit code. To unify error handling, instead of searching for particular `complain` strings, it would be interesting for kw to return a negative exit code.

**Comment by MatheusBernardino** [comment]
Shouldn't we close this issue, @rodrigosiqueira?
