### ISSUE TITLE
Add sonorous and visual alert

### ISSUE THREAD

**Issue by rodrigosiqueira** [rodrigosiqueira/kworkflow#30]
Sometimes, compilation and installation take time and we want to do something different while we wait for the end of the processes; as a result, we forgot to go back and check the compilation and wast a little bit of time. It could be nice if kw provides an option for making a sonorous and visual alert at the end of some processes.

**Comment by MatheusBernardino** [comment]
Nice one! I'm thinking about which kw commands should have this alert. I though off: build, install, new, prepare and bi. Is it good?
