### ISSUE TITLE
Use checkpatch.pl from kernel tree

### ISSUE THREAD

**Issue by matheustavares** [rodrigosiqueira/kworkflow#40]
Currently, kw uses a copy of checkpatch.pl downloaded from torvalds' repo and installed at ~/.config/kw/external. Shouldn't it be better if kw used the checkpatch.pl version that comes in scripts/ on every kernel tree? This approach would, also, be more consistent with the way kw handles and uses the get_maintainer.pl script.

**Comment by rodrigosiqueira** [comment]
Yes! You are 100% right about this inconsistency. I don't know why I added this, some legacy issue (maybe). Anyway, use the checkpatch provided by the kernel make much more sense. In PR #38 , you already made a function for finding the kernel tree; just use it for finding the checkpatch.pl.

**Comment by rodrigosiqueira** [comment]
@MatheusBernardino Could you send a PR with the feature that finds the scripts? As we already discussed in this issue, you already made in in the PR #38 . If you're busy, I can make it. Just let'me know.

**Comment by andrealmeid** [comment]
It's seems that this issue can be closed due to https://github.com/rodrigosiqueira/kworkflow/pull/107.

**Comment by matheustavares** [comment]
Oops, I just learned the existence of the `done: wait for stable` label (to be used when the issue is done but not merged into `master` yet). So I'm reopening the issue with the assigned label, for now.
