### ISSUE TITLE
Refactor miscellaneous.sh, commons.sh and utils.sh

### ISSUE THREAD

**Issue by MatheusBernardino** [rodrigosiqueira/kworkflow#41]
In the src folder, kw has a commons.sh, a miscellaneous.sh and a utils.sh, which can make a little difficult to understand the project structure for a newcomer. Can't we refactor the code to join all these files, or rename them with more meaningful names?

(If you chose to make this, keep in mind that tests uses miscellaneous.sh)

**Comment by rodrigosiqueira** [comment]
You are totally right about that. What do you think about this idea to fix the problem:

1. Move the code from utils.sh to commons (the helper)
2. Get rid of utils.sh
3. Rename miscellaneous.sh to something like kwio.sh
4. Update the required places

Do you want to work on this?
