### ISSUE TITLE
Improve README information about run_tests.sh

### ISSUE THREAD

**Issue by MatheusBernardino** [rodrigosiqueira/kworkflow#46]
The run_tests.sh script must be run from the repo's root, otherwise, it fails. We should include this information in README.md.

**Comment by rodrigosiqueira** [comment]
@MatheusBernardino 
Could you handle it?

**Comment by MatheusBernardino** [comment]
>@MatheusBernardino
>Could you handle it?

Sure! I'll do it.

**Comment by MatheusBernardino** [comment]
Solved with #58
