### ISSUE TITLE
Make kw mount and kw boot work with local configuration

### ISSUE THREAD

**Issue by MatheusBernardino** [rodrigosiqueira/kworkflow#47]
When using a local kworkflow.config file, "kw mount" and "kw boot" currently ignore the variable `${configurations[qemu_path_image]}` and use, instead, the default variable `$VDISK`. So the image to be mounted or built will always be the one pointed by `$VDISK` even when the user has a local configuration file (a kworkflow.config).

**Comment by rodrigosiqueira** [comment]
@MatheusBernardino 

Is it fixed by #54?

**Comment by MatheusBernardino** [comment]
>@MatheusBernardino
>
>Is it fixed by #54?

Yes, it's fixed. I'm closing the issue
