### ISSUE TITLE
Remove unused global configuration variables and move used to config file

### ISSUE THREAD

**Issue by MatheusBernardino** [rodrigosiqueira/kworkflow#55]
Since the movement too a global configuration file (PR #54 ), some global configuration variables will become redundant and meaningless, such as the ones at the top of commons.sh. This unused configuration variables should be removed (at commons.sh and all the code). And the ones that are still in use, but not in the global configuration file yet, should be moved to it.

**Comment by rodrigosiqueira** [comment]
Currently, I identified the following useless variables in ```commons.sh```:

```
BUILD_DIR
BASE
BASHPATH
```

**Comment by rodrigosiqueira** [comment]
Done.

https://github.com/rodrigosiqueira/kworkflow/pull/54
