### ISSUE TITLE
Improve autocomplete

### ISSUE THREAD

**Issue by MatheusBernardino** [rodrigosiqueira/kworkflow#57]
When typing a command such as `kw maintainers`, it would be really nice to have a tab completion for files. This also happens in other commands.

**Comment by MatheusBernardino** [comment]
By what I understand, @rodrigosiqueira , bash automatically uses the path completion when the command being written by the user doesn't have a custom set of completion rules. As we are using `complete -W "export ...`, bash uses that instead of path completion. The way to have both, as what I know for now, is to have a `/usr/share/bash-completion/completions/kw` file, specifying the completion process for kw (it's a bashscript). Under this directory, you can take a look at completion for other programs such as python3, for example.

The problem is that we need sudo access to this dir. Maybe we should search if bash loads completion files from other dirs, too, without the need of sudo.

**Comment by MatheusBernardino** [comment]
Just a little bit more of information I found:

- It seems we can have our file at ` ~/.local/share/bash-completion/completions`, and it does not require sudo. But that's a directory for user defined custom completions, I don't know how good it is to install a third party completion file (such as kw's) there.
- Here is a tutorial that seems to be very good at explaining how the completion files need to be (and the bash-completion's overall operation): https://iridakos.com/tutorials/2018/03/01/bash-programmable-completion-tutorial.html

**Comment by shayenne** [comment]
Hi, I was looking for solutions to this problem. I also use the first part of this tutorial to create first version of autocomplete. It does not have directory completions as examples, just autocomplete and history. But I found some examples and I will try them to improve autocomplete.

**Comment by shayenne** [comment]
Hi, I was looking for solutions to this problem. I also use the first part of this tutorial to create first version of autocomplete. It does not have directory completions as examples, just autocomplete and history. But I found some examples and I will try them to improve autocomplete.

**Comment by shayenne** [comment]
Hi! I found a way to include file autocomplete.

Now I would like to know which options need files as parameters. I just know about `maintainers` and `m`. There are parameters for others commands?

**Comment by shayenne** [comment]
I just send the PR #60 to solve this issue.

**Comment by rodrigosiqueira** [comment]
Thanks @shayenne for work in this issue! See: https://github.com/rodrigosiqueira/kworkflow/pull/60
