### ISSUE TITLE
Alert does not work on Ubuntu

### ISSUE THREAD

**Issue by shayenne** [rodrigosiqueira/kworkflow#71]
For some reason alert does not work on my Ubuntu. Follow my config file.

``qemu_hw_options=-enable-kvm` -daemonize -m 3G -smp cores=8,cpus=8
qemu_net_options=-net nic -net user,hostfwd=tcp::2222-:22,smb=/home/shayenne 
qemu_path_image=/home/shayenne/p/virty.qcow2
alert=s``

**Comment by MatheusBernardino** [comment]
Hmm, that's weird... Just to make sure, you do have `paplay` installed, right? Could you please run a kw command that uses alert and grep for the paplay process, to see if it was invoked? (something like: `kw b; ps -A | grep paplay`) @shayenne

**Comment by shayenne** [comment]
I found the issue! I did not restart the bash. Thank you, @MatheusBernardino!

**Comment by MatheusBernardino** [comment]
Nice! Glad you were able to solve it :) @shayenne
