### ISSUE TITLE
Update KW's dependencies

### ISSUE THREAD

**Issue by matheustavares** [rodrigosiqueira/kworkflow#82]
We should scan kw's source to gather all dependencies and update our dependency list at README.

**Comment by rodrigosiqueira** [comment]
Close this issue since we're fine with that, see https://siqueira.tech/doc/kw/content/installanduninstall.html

**Comment by matheustavares** [comment]
Hi @rodrigosiqueira , I think it's still missing `rsync` in the dependencies. I know it's pretty common to have it already installed these days, but I went to setup KW on a machine during an event and it failed because the person didn't have `rsync` installed. Maybe it would be good to mention that as a dependency as well. Also, should we add `fish` as a development dependency?

**Comment by rodrigosiqueira** [comment]
Nice catch! `rsync` is important to highlight in the main installation and `fish` for development.
Reopen
